// src/components/CharacterDashboard.vue
&lt;template>
  &lt;div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    &lt;div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <!-- Character Stats Panel -->
      &lt;div class="bg-white p-6 rounded-lg shadow">
        &lt;h2 class="text-xl font-bold mb-4">Character Sheet&lt;/h2>
        &lt;div v-if="character" class="space-y-4">
          &lt;div class="flex justify-between items-center">
            &lt;span class="font-medium">{{ character.name }}&lt;/span>
            &lt;span>Level {{ character.level }}&lt;/span>
          &lt;/div>
          &lt;div class="flex justify-between items-center">
            &lt;span>{{ character.race }}&lt;/span>
            &lt;span>{{ character.class }}&lt;/span>
          &lt;/div>
          &lt;div class="grid grid-cols-2 gap-4">
            &lt;div v-for="(value, stat) in character.stats" :key="stat" class="bg-gray-50 p-2 rounded">
              &lt;div class="text-sm text-gray-500">{{ stat.charAt(0).toUpperCase() + stat.slice(1) }}&lt;/div>
              &lt;div class="text-lg font-medium">{{ value }}&lt;/div>
            &lt;/div>
          &lt;/div>
          &lt;div class="mt-4">
            &lt;div class="text-sm text-gray-500">Battle Tokens&lt;/div>
            &lt;div class="text-lg font-medium">{{ character.battleTokens }}&lt;/div>
          &lt;/div>
        &lt;/div>
      &lt;/div>

      <!-- Habits Panel -->
      &lt;div class="md:col-span-2 bg-white p-6 rounded-lg shadow">
        &lt;div class="flex justify-between items-center mb-4">
          &lt;h2 class="text-xl font-bold">Habits&lt;/h2>
          &lt;button
            @click="showNewHabitModal = true"
            class="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"
          >
            Add Habit
          &lt;/button>
        &lt;/div>

        &lt;div v-if="habits.length === 0" class="text-center py-8 text-gray-500">
          No habits yet. Create one to begin your journey!
        &lt;/div>

        &lt;div v-else class="space-y-4">
          &lt;div
            v-for="habit in habits"
            :key="habit.id"
            class="flex items-center justify-between p-4 bg-gray-50 rounded-lg"
          >
            &lt;div>
              &lt;h3 class="font-medium">{{ habit.name }}&lt;/h3>
              &lt;p class="text-sm text-gray-500">{{ habit.description }}&lt;/p>
              &lt;div class="flex space-x-2 mt-1">
                &lt;span class="text-xs px-2 py-1 bg-blue-100 text-blue-800 rounded">
                  {{ habit.associatedStat }}
                &lt;/span>
                &lt;span class="text-xs px-2 py-1 bg-purple-100 text-purple-800 rounded">
                  {{ habit.difficulty }}
                &lt;/span>
                &lt;span class="text-xs px-2 py-1 bg-green-100 text-green-800 rounded">
                  Streak: {{ habit.streak }}
                &lt;/span>
              &lt;/div>
            &lt;/div>
            &lt;button
              @click="completeHabit(habit.id)"
              :disabled="habit.completed"
              :class="[
                'px-4 py-2 rounded-md',
                habit.completed
                  ? 'bg-gray-300 cursor-not-allowed'
                  : 'bg-green-600 hover:bg-green-700 text-white'
              ]"
            >
              {{ habit.completed ? 'Completed' : 'Complete' }}
            &lt;/button>
          &lt;/div>
        &lt;/div>
      &lt;/div>
    &lt;/div>

    <!-- New Habit Modal -->
    &lt;div v-if="showNewHabitModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center">
      &lt;div class="bg-white p-6 rounded-lg w-full max-w-md">
        &lt;h3 class="text-lg font-bold mb-4">Create New Habit&lt;/h3>
        &lt;form @submit.prevent="createHabit" class="space-y-4">
          &lt;div>
            &lt;label class="block text-sm font-medium text-gray-700">Name&lt;/label>
            &lt;input
              v-model="newHabit.name"
              type="text"
              required
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            />
          &lt;/div>

          &lt;div>
            &lt;label class="block text-sm font-medium text-gray-700">Description&lt;/label>
            &lt;textarea
              v-model="newHabit.description"
              required
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            >&lt;/textarea>
          &lt;/div>

          &lt;div>
            &lt;label class="block text-sm font-medium text-gray-700">Associated Stat&lt;/label>
            &lt;select
              v-model="newHabit.associatedStat"
              required
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            >
              &lt;option value="strength">Strength&lt;/option>
              &lt;option value="dexterity">Dexterity&lt;/option>
              &lt;option value="constitution">Constitution&lt;/option>
              &lt;option value="intelligence">Intelligence&lt;/option>
              &lt;option value="wisdom">Wisdom&lt;/option>
              &lt;option value="charisma">Charisma&lt;/option>
            &lt;/select>
          &lt;/div>

          &lt;div>
            &lt;label class="block text-sm font-medium text-gray-700">Difficulty&lt;/label>
            &lt;select
              v-model="newHabit.difficulty"
              required
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            >
              &lt;option value="easy">Easy&lt;/option>
              &lt;option value="medium">Medium&lt;/option>
              &lt;option value="hard">Hard&lt;/option>
            &lt;/select>
          &lt;/div>

          &lt;div>
            &lt;label class="block text-sm font-medium text-gray-700">Frequency&lt;/label>
            &lt;select
              v-model="newHabit.frequency"
              required
              class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
            >
              &lt;option value="daily">Daily&lt;/option>
              &lt;option value="weekly">Weekly&lt;/option>
            &lt;/select>
          &lt;/div>

          &lt;div class="flex space-x-4">
            &lt;button
              type="submit"
              class="flex-1 py-2 px-4 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"
            >
              Create
            &lt;/button>
            &lt;button
              type="button"
              @click="showNewHabitModal = false"
              class="flex-1 py-2 px-4 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300"
            >
              Cancel
            &lt;/button>
          &lt;/div>
        &lt;/form>
      &lt;/div>
    &lt;/div>
  &lt;/div>
&lt;/template>

&lt;script setup lang="ts">
import { ref, computed } from 'vue';
import { useCharacterStore } from '../stores/characterStore';
import type { Habit } from '../types/character';

const characterStore = useCharacterStore();
const character = computed(() => characterStore.character);
const habits = computed(() => characterStore.getHabits);

const showNewHabitModal = ref(false);
const newHabit = ref({
  name: '',
  description: '',
  frequency: 'daily',
  difficulty: 'easy',
  associatedStat: 'strength',
});

const createHabit = async () => {
  await characterStore.addHabit(newHabit.value);
  showNewHabitModal.value = false;
  newHabit.value = {
    name: '',
    description: '',
    frequency: 'daily',
    difficulty: 'easy',
    associatedStat: 'strength',
  };
};

const completeHabit = async (habitId: string) => {
  await characterStore.completeHabit(habitId);
};
&lt;/script>

// src/components/CharacterDashboard.tsx
import React, { useState, useMemo, useEffect } from 'react';
import { useUserStore } from '../stores/userStore';
import { CheckCircle, Circle, Flame, Calendar, Sword, Shield, Heart, Brain, Eye, MessageCircle, TrendingUp } from 'lucide-react';
import type { CharacterStats } from '../types/character';

export function CharacterDashboard() {
  const user = useUserStore((state) => state.user);
  const addHabit = useUserStore((state) => state.addHabit);
  const completeHabit = useUserStore((state) => state.completeHabit);
  const character = user?.character;

  useEffect(() => {
    if (character) {
      console.log('Character:', {
        stats: character.stats,
        habits: character.habits.map(h => ({
          name: h.name,
          streak: h.streak,
          completed: h.completed,
          associatedStat: h.associatedStat
        }))
      });
    }
  }, [character]);

  const [showNewHabitModal, setShowNewHabitModal] = useState(false);
  const [newHabit, setNewHabit] = useState({
    name: '',
    description: '',
    frequency: 'daily',
    difficulty: 'easy',
    associatedStat: 'strength',
  });

  // Calculate stat buffs from habit streaks
  const statBuffs = useMemo(() => {
    if (!character?.habits) return {};

    const buffs: Partial<CharacterStats> = {};
    
    character.habits.forEach(habit => {
      if (habit.streak > 0) {
        const stat = habit.associatedStat as keyof CharacterStats;
        // Increase buff amount to make it more noticeable
        const buffAmount = Math.floor(habit.streak); // 1 point per streak level
        buffs[stat] = (buffs[stat] || 0) + buffAmount;
      }
    });

    console.log('Calculating buffs:', {
      habits: character.habits.map(h => ({
        name: h.name,
        streak: h.streak,
        stat: h.associatedStat,
        buffAmount: h.streak > 0 ? Math.floor(h.streak) : 0
      })),
      calculatedBuffs: buffs
    });

    return buffs;
  }, [character?.habits]);

  useEffect(() => {
    console.log('Stat buffs:', statBuffs);
  }, [statBuffs]);

  // Reset completed status of habits daily
  useEffect(() => {
    const resetHabits = () => {
      if (!character?.habits) return;
      
      const now = new Date();
      const lastReset = localStorage.getItem('lastHabitReset');
      const lastResetDate = lastReset ? new Date(lastReset) : null;
      
      if (!lastResetDate || lastResetDate.getDate() !== now.getDate()) {
        character.habits.forEach(habit => {
          if (habit.completed) {
            completeHabit(habit.id); // This will update the streak
          }
        });
        localStorage.setItem('lastHabitReset', now.toISOString());
      }
    };

    resetHabits();
    const interval = setInterval(resetHabits, 60000); // Check every minute
    return () => clearInterval(interval);
  }, [character?.habits, completeHabit]);

  const handleCreateHabit = (e: React.FormEvent) => {
    e.preventDefault();
    addHabit(newHabit);
    setNewHabit({
      name: '',
      description: '',
      frequency: 'daily',
      difficulty: 'easy',
      associatedStat: 'strength',
    });
    setShowNewHabitModal(false);
  };

  const handleCompleteHabit = (habitId: string) => {
    completeHabit(habitId);
  };

  const getStatIcon = (stat: string) => {
    const icons = {
      strength: Sword,
      dexterity: Shield,
      constitution: Heart,
      intelligence: Brain,
      wisdom: Eye,
      charisma: MessageCircle
    };
    const Icon = icons[stat as keyof typeof icons];
    return Icon ? <Icon className="w-5 h-5" /> : null;
  };

  const getDifficultyColor = (difficulty: string) => {
    switch (difficulty) {
      case 'trivial': return 'bg-gray-700 text-gray-300';
      case 'easy': return 'bg-green-900/40 text-green-300';
      case 'medium': return 'bg-yellow-900/40 text-yellow-300';
      case 'hard': return 'bg-red-900/40 text-red-300';
      default: return 'bg-gray-700 text-gray-300';
    }
  };

  const getStreakBonus = (streak: number) => {
    const multiplier = Math.min(1 + (streak * 0.1), 2.0);
    return `${Math.round(multiplier * 100)}%`;
  };

  return (
    <div className="space-y-6">
      {/* Character Stats Panel */}
      <div className="bg-gray-900 p-6 rounded-xl shadow-xl text-gray-100">
        <h2 className="text-3xl font-bold mb-2">{character?.name || 'Adventurer'}</h2>
        <p className="text-gray-400 mb-6">
          Level {character?.level || 1} {character?.race || 'Human'} {character?.class || 'Fighter'}
        </p>
        
        <div className="grid grid-cols-2 gap-4">
          {character?.stats && Object.entries(character.stats).map(([stat, value]) => {
            const buff = statBuffs[stat as keyof CharacterStats] || 0;
            console.log(`Rendering stat ${stat}:`, { baseValue: value, buff });
            return (
              <div key={stat} className="bg-gray-800 p-4 rounded-lg flex items-start gap-3">
                {getStatIcon(stat)}
                <div className="flex-1">
                  <div className="text-gray-400 text-sm">
                    {stat.charAt(0).toUpperCase() + stat.slice(1)}
                  </div>
                  <div className="flex items-baseline gap-2">
                    <span className="text-2xl font-bold text-white">{value}</span>
                    {buff > 0 && (
                      <span className="text-sm text-green-400">+{buff}</span>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        <div className="grid grid-cols-2 gap-4 mt-6">
          <div className="bg-gray-800 p-4 rounded-lg">
            <div className="text-gray-400 text-sm">Experience</div>
            <div className="text-xl font-bold">{character?.experience || 0} XP</div>
          </div>
          <div className="bg-gray-800 p-4 rounded-lg">
            <div className="text-gray-400 text-sm">Battle Tokens</div>
            <div className="text-xl font-bold flex items-center gap-2">
              {character?.battleTokens || 0}
              <div className="w-5 h-5 bg-gray-600 rounded-full"/>
            </div>
          </div>
        </div>
      </div>

      {/* Habits Panel */}
      <div className="bg-gray-900 p-6 rounded-xl shadow-xl text-gray-100">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold">Daily Quests</h2>
          <button
            onClick={() => setShowNewHabitModal(true)}
            className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-900"
          >
            Add Quest
          </button>
        </div>

        {(!character?.habits || character.habits.length === 0) ? (
          <div className="text-center py-8 text-gray-400">
            No quests yet. Add one to begin your journey!
          </div>
        ) : (
          <div className="space-y-4">
            {character.habits.map(habit => (
              <div
                key={habit.id}
                className={`flex items-center justify-between p-4 rounded-lg ${
                  habit.completed ? 'bg-green-900/20' : 'bg-gray-800 hover:bg-gray-700'
                }`}
              >
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold">{habit.name}</h3>
                    {habit.streak > 0 && (
                      <div className="flex items-center gap-1 text-orange-400">
                        <Flame className="w-4 h-4" />
                        <span className="text-sm">{habit.streak}</span>
                      </div>
                    )}
                  </div>
                  
                  <p className="text-sm text-gray-400">{habit.description}</p>
                  
                  <div className="flex items-center gap-2 mt-2">
                    <span className={`text-xs px-2 py-1 rounded ${getDifficultyColor(habit.difficulty)}`}>
                      {habit.difficulty}
                    </span>
                    <span className="text-xs text-gray-400">
                      Affects {habit.associatedStat}
                    </span>
                    {habit.streak > 0 && (
                      <span className="text-xs text-orange-400">
                        Bonus: {getStreakBonus(habit.streak)}
                      </span>
                    )}
                  </div>

                  {habit.schedule && (
                    <div className="flex items-center gap-1 mt-2 text-xs text-gray-400">
                      <Calendar className="w-4 h-4" />
                      <span>
                        {Object.entries(habit.schedule)
                          .filter(([_, active]) => active)
                          .map(([day]) => day.charAt(0).toUpperCase())
                          .join(', ')}
                      </span>
                    </div>
                  )}
                </div>

                <button
                  onClick={() => handleCompleteHabit(habit.id)}
                  disabled={habit.completed}
                  className={`ml-4 p-2 rounded-full transition-colors ${
                    habit.completed
                      ? 'bg-green-500/20 text-green-400'
                      : 'hover:bg-gray-600 text-gray-400'
                  }`}
                >
                  {habit.completed ? <CheckCircle className="w-6 h-6" /> : <Circle className="w-6 h-6" />}
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* New Habit Modal */}
      {showNewHabitModal && (
        <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center">
          <div className="bg-gray-900 p-6 rounded-xl w-full max-w-md text-gray-100">
            <h3 className="text-xl font-bold mb-4">Create New Quest</h3>
            <form onSubmit={handleCreateHabit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-400">Name</label>
                <input
                  type="text"
                  value={newHabit.name}
                  onChange={(e) => setNewHabit({ ...newHabit, name: e.target.value })}
                  required
                  className="mt-1 block w-full rounded-md bg-gray-800 border-gray-700 text-gray-100 focus:border-indigo-500 focus:ring-indigo-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-400">Description</label>
                <textarea
                  value={newHabit.description}
                  onChange={(e) => setNewHabit({ ...newHabit, description: e.target.value })}
                  required
                  className="mt-1 block w-full rounded-md bg-gray-800 border-gray-700 text-gray-100 focus:border-indigo-500 focus:ring-indigo-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-400">Associated Stat</label>
                <select
                  value={newHabit.associatedStat}
                  onChange={(e) => setNewHabit({ ...newHabit, associatedStat: e.target.value })}
                  required
                  className="mt-1 block w-full rounded-md bg-gray-800 border-gray-700 text-gray-100 focus:border-indigo-500 focus:ring-indigo-500"
                >
                  <option value="strength">Strength</option>
                  <option value="dexterity">Dexterity</option>
                  <option value="constitution">Constitution</option>
                  <option value="intelligence">Intelligence</option>
                  <option value="wisdom">Wisdom</option>
                  <option value="charisma">Charisma</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-400">Difficulty</label>
                <select
                  value={newHabit.difficulty}
                  onChange={(e) => setNewHabit({ ...newHabit, difficulty: e.target.value })}
                  required
                  className="mt-1 block w-full rounded-md bg-gray-800 border-gray-700 text-gray-100 focus:border-indigo-500 focus:ring-indigo-500"
                >
                  <option value="trivial">Trivial</option>
                  <option value="easy">Easy</option>
                  <option value="medium">Medium</option>
                  <option value="hard">Hard</option>
                </select>
              </div>

              <div className="flex gap-4 mt-6">
                <button
                  type="submit"
                  className="flex-1 py-2 px-4 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-900"
                >
                  Create
                </button>
                <button
                  type="button"
                  onClick={() => setShowNewHabitModal(false)}
                  className="flex-1 py-2 px-4 bg-gray-800 text-gray-300 rounded-md hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 focus:ring-offset-gray-900"
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
